import { Listener } from "./apis/listen.js";

import { changeGroupOwnerFactory } from "./apis/changeGroupOwner.js";
import { getLabelsFactory } from "./apis/getLabels.js";
import { acceptFriendRequestFactory } from "./apis/acceptFriendRequest.js";
import { resetHiddenConversPinFactory } from "./apis/resetHiddenConversPin.js";
import { getGroupLinkInfoFactory } from "./apis/getGroupLinkInfo.js";
import { editNoteFactory } from "./apis/editNote.js";
import { sharePollFactory } from "./apis/sharePoll.js";
import { updateAutoDeleteChatFactory } from "./apis/updateAutoDeleteChat.js";
import { getCloseFriendsFactory } from "./apis/getCloseFriends.js";
import { votePollFactory } from "./apis/votePoll.js";
import { getGroupInfoFactory } from "./apis/getGroupInfo.js";
import { deleteChatFactory } from "./apis/deleteChat.js";
import { removeFriendFactory } from "./apis/removeFriend.js";
import { addPollOptionsFactory } from "./apis/addPollOptions.js";
import { getOwnIdFactory } from "./apis/getOwnId.js";
import { deleteGroupInviteBoxFactory } from "./apis/deleteGroupInviteBox.js";
import { rejectFriendRequestFactory } from "./apis/rejectFriendRequest.js";
import { removeGroupDeputyFactory } from "./apis/removeGroupDeputy.js";
import { createNoteFactory } from "./apis/createNote.js";
import { updateActiveStatusFactory } from "./apis/updateActiveStatus.js";
import { blockUserFactory } from "./apis/blockUser.js";
import { changeGroupAvatarFactory } from "./apis/changeGroupAvatar.js";
import { deleteAutoReplyFactory } from "./apis/deleteAutoReply.js";
import { getPinConversationsFactory } from "./apis/getPinConversations.js";
import { updateCatalogFactory } from "./apis/updateCatalog.js";
import { upgradeGroupToCommunityFactory } from "./apis/upgradeGroupToCommunity.js";
import { getGroupMembersInfoFactory } from "./apis/getGroupMembersInfo.js";
import { getAvatarListFactory } from "./apis/getAvatarList.js";
import { getFriendRecommendationsFactory } from "./apis/getFriendRecommendations.js";
import { updateProfileBioFactory } from "./apis/updateProfileBio.js";
import { removeReminderFactory } from "./apis/removeReminder.js";
import { sendMessageFactory } from "./apis/sendMessage.js";
import { setMuteFactory } from "./apis/setMute.js";
import { removeGroupBlockedMemberFactory } from "./apis/removeGroupBlockedMember.js";
import { updateLangFactory } from "./apis/updateLang.js";
import { undoFactory } from "./apis/undo.js";
import { getHiddenConversationsFactory } from "./apis/getHiddenConversations.js";
import { parseLinkFactory } from "./apis/parseLink.js";
import { setPinnedConversationsFactory } from "./apis/setPinnedConversations.js";
import { addUserToGroupFactory } from "./apis/addUserToGroup.js";
import { disableGroupLinkFactory } from "./apis/disableGroupLink.js";
import { setHiddenConversationsFactory } from "./apis/setHiddenConversations.js";
import { getSettingsFactory } from "./apis/getSettings.js";
import { deleteAvatarFactory } from "./apis/deleteAvatar.js";
import { getGroupChatHistoryFactory } from "./apis/getGroupChatHistory.js";
import { getAliasListFactory } from "./apis/getAliasList.js";
import { fetchAccountInfoFactory } from "./apis/fetchAccountInfo.js";
import { getProductCatalogListFactory } from "./apis/getProductCatalogList.js";
import { removeQuickMessageFactory } from "./apis/removeQuickMessage.js";
import { getUnreadMarkFactory } from "./apis/getUnreadMark.js";
import { updateLabelsFactory } from "./apis/updateLabels.js";
import { changeGroupNameFactory } from "./apis/changeGroupName.js";
import { getGroupLinkDetailFactory } from "./apis/getGroupLinkDetail.js";
import { getPollDetailFactory } from "./apis/getPollDetail.js";
import { sendVoiceFactory } from "./apis/sendVoice.js";
import { getFriendOnlinesFactory } from "./apis/getFriendOnlines.js";
import { getAllGroupsFactory } from "./apis/getAllGroups.js";
import { createPollFactory } from "./apis/createPoll.js";
import { getPendingGroupMembersFactory } from "./apis/getPendingGroupMembers.js";
import { createGroupFactory } from "./apis/createGroup.js";
import { inviteUserToGroupsFactory } from "./apis/inviteUserToGroups.js";
import { getListBoardFactory } from "./apis/getListBoard.js";
import { getContextFactory } from "./apis/getContext.js";
import { getReminderResponsesFactory } from "./apis/getReminderResponses.js";
import { getAvatarUrlProfileFactory } from "./apis/getAvatarUrlProfile.js";
import { getQuickMessageListFactory } from "./apis/getQuickMessageList.js";
import { getBizAccountFactory } from "./apis/getBizAccount.js";
import { uploadProductPhotoFactory } from "./apis/uploadProductPhoto.js";
import { disperseGroupFactory } from "./apis/disperseGroup.js";
import { updateSettingsFactory } from "./apis/updateSettings.js";
import { uploadAttachmentFactory } from "./apis/uploadAttachment.js";
import { deleteMessageFactory } from "./apis/deleteMessage.js";
import { updateProductCatalogFactory } from "./apis/updateProductCatalog.js";
import { createProductCatalogFactory } from "./apis/createProductCatalog.js";
import { getAutoReplyListFactory } from "./apis/getAutoReplyList.js";
import { reuseAvatarFactory } from "./apis/reuseAvatar.js";
import { getStickerCategoryDetailFactory } from "./apis/getStickerCategoryDetail.js";
import { getAllFriendsFactory } from "./apis/getAllFriends.js";
import { findUserFactory } from "./apis/findUser.js";
import { sendCardFactory } from "./apis/sendCard.js";
import { changeAccountAvatarFactory } from "./apis/changeAccountAvatar.js";
import { removeUserFromGroupFactory } from "./apis/removeUserFromGroup.js";
import { removeFriendAliasFactory } from "./apis/removeFriendAlias.js";
import { getFriendBoardListFactory } from "./apis/getFriendBoardList.js";
import { editReminderFactory } from "./apis/editReminder.js";
import { createAutoReplyFactory } from "./apis/createAutoReply.js";
import { updateProfileFactory } from "./apis/updateProfile.js";
import { lastOnlineFactory } from "./apis/lastOnline.js";
import { addUnreadMarkFactory } from "./apis/addUnreadMark.js";
import { createCatalogFactory } from "./apis/createCatalog.js";
import { getStickersFactory } from "./apis/getStickers.js";
import { unblockUserFactory } from "./apis/unblockUser.js";
import { getQRFactory } from "./apis/getQR.js";
import { joinGroupInviteBoxFactory } from "./apis/joinGroupInviteBox.js";
import { addReactionFactory } from "./apis/addReaction.js";
import { getAutoDeleteChatFactory } from "./apis/getAutoDeleteChat.js";
import { reviewPendingMemberRequestFactory } from "./apis/reviewPendingMemberRequest.js";
import { searchStickerFactory } from "./apis/searchSticker.js";
import { getUserInfoFactory } from "./apis/getUserInfo.js";
import { getMultiUsersByPhonesFactory } from "./apis/getMultiUsersByPhones.js";
import { updateGroupSettingsFactory } from "./apis/updateGroupSettings.js";
import { getFriendRequestStatusFactory } from "./apis/getFriendRequestStatus.js";
import { sendBankCardFactory } from "./apis/sendBankCard.js";
import { getFullAvatarFactory } from "./apis/getFullAvatar.js";
import { getSentFriendRequestFactory } from "./apis/getSentFriendRequest.js";
import { getGroupBlockedMemberFactory } from "./apis/getGroupBlockedMember.js";
import { sendFriendRequestFactory } from "./apis/sendFriendRequest.js";
import { getReminderFactory } from "./apis/getReminder.js";
import { getListReminderFactory } from "./apis/getListReminder.js";
import { deleteCatalogFactory } from "./apis/deleteCatalog.js";
import { sendSeenEventFactory } from "./apis/sendSeenEvent.js";
import { updateHiddenConversPinFactory } from "./apis/updateHiddenConversPin.js";
import { blockViewFeedFactory } from "./apis/blockViewFeed.js";
import { addGroupBlockedMemberFactory } from "./apis/addGroupBlockedMember.js";
import { sendDeliveredEventFactory } from "./apis/sendDeliveredEvent.js";
import { removeUnreadMarkFactory } from "./apis/removeUnreadMark.js";
import { leaveGroupFactory } from "./apis/leaveGroup.js";
import { getGroupInviteBoxInfoFactory } from "./apis/getGroupInviteBoxInfo.js";
import { addQuickMessageFactory } from "./apis/addQuickMessage.js";
import { sendLinkFactory } from "./apis/sendLink.js";
import { getMuteFactory } from "./apis/getMute.js";
import { sendTypingEventFactory } from "./apis/sendTypingEvent.js";
import { getCatalogListFactory } from "./apis/getCatalogList.js";
import { getRelatedFriendGroupFactory } from "./apis/getRelatedFriendGroup.js";
import { deleteProductCatalogFactory } from "./apis/deleteProductCatalog.js";
import { getGroupInviteBoxListFactory } from "./apis/getGroupInviteBoxList.js";
import { findUserByUsernameFactory } from "./apis/findUserByUsername.js";
import { enableGroupLinkFactory } from "./apis/enableGroupLink.js";
import { changeFriendAliasFactory } from "./apis/changeFriendAlias.js";
import { forwardMessageFactory } from "./apis/forwardMessage.js";
import { undoFriendRequestFactory } from "./apis/undoFriendRequest.js";
import { joinGroupLinkFactory } from "./apis/joinGroupLink.js";
import { getStickersDetailFactory } from "./apis/getStickersDetail.js";
import { createReminderFactory } from "./apis/createReminder.js";
import { addGroupDeputyFactory } from "./apis/addGroupDeputy.js";
import { getCookieFactory } from "./apis/getCookie.js";
import { keepAliveFactory } from "./apis/keepAlive.js";
import { lockPollFactory } from "./apis/lockPoll.js";
import { sendReportFactory } from "./apis/sendReport.js";
import { sendVideoFactory } from "./apis/sendVideo.js";
import { updateQuickMessageFactory } from "./apis/updateQuickMessage.js";
import { updateArchivedChatListFactory } from "./apis/updateArchivedChatList.js";
import { sendStickerFactory } from "./apis/sendSticker.js";
import { getArchivedChatListFactory } from "./apis/getArchivedChatList.js";
import { updateAutoReplyFactory } from "./apis/updateAutoReply.js";
import { customFactory } from "./apis/custom.js";
import type { ZPWServiceMap, ContextSession } from "./context.js";

export class API {
    public zpwServiceMap: ZPWServiceMap;
    public listener: Listener;

    public changeGroupOwner: ReturnType<typeof changeGroupOwnerFactory>;
    public getLabels: ReturnType<typeof getLabelsFactory>;
    public acceptFriendRequest: ReturnType<typeof acceptFriendRequestFactory>;
    public resetHiddenConversPin: ReturnType<typeof resetHiddenConversPinFactory>;
    public getGroupLinkInfo: ReturnType<typeof getGroupLinkInfoFactory>;
    public editNote: ReturnType<typeof editNoteFactory>;
    public sharePoll: ReturnType<typeof sharePollFactory>;
    public updateAutoDeleteChat: ReturnType<typeof updateAutoDeleteChatFactory>;
    public getCloseFriends: ReturnType<typeof getCloseFriendsFactory>;
    public votePoll: ReturnType<typeof votePollFactory>;
    public getGroupInfo: ReturnType<typeof getGroupInfoFactory>;
    public deleteChat: ReturnType<typeof deleteChatFactory>;
    public removeFriend: ReturnType<typeof removeFriendFactory>;
    public addPollOptions: ReturnType<typeof addPollOptionsFactory>;
    public getOwnId: ReturnType<typeof getOwnIdFactory>;
    public deleteGroupInviteBox: ReturnType<typeof deleteGroupInviteBoxFactory>;
    public rejectFriendRequest: ReturnType<typeof rejectFriendRequestFactory>;
    public removeGroupDeputy: ReturnType<typeof removeGroupDeputyFactory>;
    public createNote: ReturnType<typeof createNoteFactory>;
    public updateActiveStatus: ReturnType<typeof updateActiveStatusFactory>;
    public blockUser: ReturnType<typeof blockUserFactory>;
    public changeGroupAvatar: ReturnType<typeof changeGroupAvatarFactory>;
    public deleteAutoReply: ReturnType<typeof deleteAutoReplyFactory>;
    public getPinConversations: ReturnType<typeof getPinConversationsFactory>;
    public updateCatalog: ReturnType<typeof updateCatalogFactory>;
    public upgradeGroupToCommunity: ReturnType<typeof upgradeGroupToCommunityFactory>;
    public getGroupMembersInfo: ReturnType<typeof getGroupMembersInfoFactory>;
    public getAvatarList: ReturnType<typeof getAvatarListFactory>;
    public getFriendRecommendations: ReturnType<typeof getFriendRecommendationsFactory>;
    public updateProfileBio: ReturnType<typeof updateProfileBioFactory>;
    public removeReminder: ReturnType<typeof removeReminderFactory>;
    public sendMessage: ReturnType<typeof sendMessageFactory>;
    public setMute: ReturnType<typeof setMuteFactory>;
    public removeGroupBlockedMember: ReturnType<typeof removeGroupBlockedMemberFactory>;
    public updateLang: ReturnType<typeof updateLangFactory>;
    public undo: ReturnType<typeof undoFactory>;
    public getHiddenConversations: ReturnType<typeof getHiddenConversationsFactory>;
    public parseLink: ReturnType<typeof parseLinkFactory>;
    public setPinnedConversations: ReturnType<typeof setPinnedConversationsFactory>;
    public addUserToGroup: ReturnType<typeof addUserToGroupFactory>;
    public disableGroupLink: ReturnType<typeof disableGroupLinkFactory>;
    public setHiddenConversations: ReturnType<typeof setHiddenConversationsFactory>;
    public getSettings: ReturnType<typeof getSettingsFactory>;
    public deleteAvatar: ReturnType<typeof deleteAvatarFactory>;
    public getGroupChatHistory: ReturnType<typeof getGroupChatHistoryFactory>;
    public getAliasList: ReturnType<typeof getAliasListFactory>;
    public fetchAccountInfo: ReturnType<typeof fetchAccountInfoFactory>;
    public getProductCatalogList: ReturnType<typeof getProductCatalogListFactory>;
    public removeQuickMessage: ReturnType<typeof removeQuickMessageFactory>;
    public getUnreadMark: ReturnType<typeof getUnreadMarkFactory>;
    public updateLabels: ReturnType<typeof updateLabelsFactory>;
    public changeGroupName: ReturnType<typeof changeGroupNameFactory>;
    public getGroupLinkDetail: ReturnType<typeof getGroupLinkDetailFactory>;
    public getPollDetail: ReturnType<typeof getPollDetailFactory>;
    public sendVoice: ReturnType<typeof sendVoiceFactory>;
    public getFriendOnlines: ReturnType<typeof getFriendOnlinesFactory>;
    public getAllGroups: ReturnType<typeof getAllGroupsFactory>;
    public createPoll: ReturnType<typeof createPollFactory>;
    public getPendingGroupMembers: ReturnType<typeof getPendingGroupMembersFactory>;
    public createGroup: ReturnType<typeof createGroupFactory>;
    public inviteUserToGroups: ReturnType<typeof inviteUserToGroupsFactory>;
    public getListBoard: ReturnType<typeof getListBoardFactory>;
    public getContext: ReturnType<typeof getContextFactory>;
    public getReminderResponses: ReturnType<typeof getReminderResponsesFactory>;
    public getAvatarUrlProfile: ReturnType<typeof getAvatarUrlProfileFactory>;
    public getQuickMessageList: ReturnType<typeof getQuickMessageListFactory>;
    public getBizAccount: ReturnType<typeof getBizAccountFactory>;
    public uploadProductPhoto: ReturnType<typeof uploadProductPhotoFactory>;
    public disperseGroup: ReturnType<typeof disperseGroupFactory>;
    public updateSettings: ReturnType<typeof updateSettingsFactory>;
    public uploadAttachment: ReturnType<typeof uploadAttachmentFactory>;
    public deleteMessage: ReturnType<typeof deleteMessageFactory>;
    public updateProductCatalog: ReturnType<typeof updateProductCatalogFactory>;
    public createProductCatalog: ReturnType<typeof createProductCatalogFactory>;
    public getAutoReplyList: ReturnType<typeof getAutoReplyListFactory>;
    public reuseAvatar: ReturnType<typeof reuseAvatarFactory>;
    public getStickerCategoryDetail: ReturnType<typeof getStickerCategoryDetailFactory>;
    public getAllFriends: ReturnType<typeof getAllFriendsFactory>;
    public findUser: ReturnType<typeof findUserFactory>;
    public sendCard: ReturnType<typeof sendCardFactory>;
    public changeAccountAvatar: ReturnType<typeof changeAccountAvatarFactory>;
    public removeUserFromGroup: ReturnType<typeof removeUserFromGroupFactory>;
    public removeFriendAlias: ReturnType<typeof removeFriendAliasFactory>;
    public getFriendBoardList: ReturnType<typeof getFriendBoardListFactory>;
    public editReminder: ReturnType<typeof editReminderFactory>;
    public createAutoReply: ReturnType<typeof createAutoReplyFactory>;
    public updateProfile: ReturnType<typeof updateProfileFactory>;
    public lastOnline: ReturnType<typeof lastOnlineFactory>;
    public addUnreadMark: ReturnType<typeof addUnreadMarkFactory>;
    public createCatalog: ReturnType<typeof createCatalogFactory>;
    public getStickers: ReturnType<typeof getStickersFactory>;
    public unblockUser: ReturnType<typeof unblockUserFactory>;
    public getQR: ReturnType<typeof getQRFactory>;
    public joinGroupInviteBox: ReturnType<typeof joinGroupInviteBoxFactory>;
    public addReaction: ReturnType<typeof addReactionFactory>;
    public getAutoDeleteChat: ReturnType<typeof getAutoDeleteChatFactory>;
    public reviewPendingMemberRequest: ReturnType<typeof reviewPendingMemberRequestFactory>;
    public searchSticker: ReturnType<typeof searchStickerFactory>;
    public getUserInfo: ReturnType<typeof getUserInfoFactory>;
    public getMultiUsersByPhones: ReturnType<typeof getMultiUsersByPhonesFactory>;
    public updateGroupSettings: ReturnType<typeof updateGroupSettingsFactory>;
    public getFriendRequestStatus: ReturnType<typeof getFriendRequestStatusFactory>;
    public sendBankCard: ReturnType<typeof sendBankCardFactory>;
    public getFullAvatar: ReturnType<typeof getFullAvatarFactory>;
    public getSentFriendRequest: ReturnType<typeof getSentFriendRequestFactory>;
    public getGroupBlockedMember: ReturnType<typeof getGroupBlockedMemberFactory>;
    public sendFriendRequest: ReturnType<typeof sendFriendRequestFactory>;
    public getReminder: ReturnType<typeof getReminderFactory>;
    public getListReminder: ReturnType<typeof getListReminderFactory>;
    public deleteCatalog: ReturnType<typeof deleteCatalogFactory>;
    public sendSeenEvent: ReturnType<typeof sendSeenEventFactory>;
    public updateHiddenConversPin: ReturnType<typeof updateHiddenConversPinFactory>;
    public blockViewFeed: ReturnType<typeof blockViewFeedFactory>;
    public addGroupBlockedMember: ReturnType<typeof addGroupBlockedMemberFactory>;
    public sendDeliveredEvent: ReturnType<typeof sendDeliveredEventFactory>;
    public removeUnreadMark: ReturnType<typeof removeUnreadMarkFactory>;
    public leaveGroup: ReturnType<typeof leaveGroupFactory>;
    public getGroupInviteBoxInfo: ReturnType<typeof getGroupInviteBoxInfoFactory>;
    public addQuickMessage: ReturnType<typeof addQuickMessageFactory>;
    public sendLink: ReturnType<typeof sendLinkFactory>;
    public getMute: ReturnType<typeof getMuteFactory>;
    public sendTypingEvent: ReturnType<typeof sendTypingEventFactory>;
    public getCatalogList: ReturnType<typeof getCatalogListFactory>;
    public getRelatedFriendGroup: ReturnType<typeof getRelatedFriendGroupFactory>;
    public deleteProductCatalog: ReturnType<typeof deleteProductCatalogFactory>;
    public getGroupInviteBoxList: ReturnType<typeof getGroupInviteBoxListFactory>;
    public findUserByUsername: ReturnType<typeof findUserByUsernameFactory>;
    public enableGroupLink: ReturnType<typeof enableGroupLinkFactory>;
    public changeFriendAlias: ReturnType<typeof changeFriendAliasFactory>;
    public forwardMessage: ReturnType<typeof forwardMessageFactory>;
    public undoFriendRequest: ReturnType<typeof undoFriendRequestFactory>;
    public joinGroupLink: ReturnType<typeof joinGroupLinkFactory>;
    public getStickersDetail: ReturnType<typeof getStickersDetailFactory>;
    public createReminder: ReturnType<typeof createReminderFactory>;
    public addGroupDeputy: ReturnType<typeof addGroupDeputyFactory>;
    public getCookie: ReturnType<typeof getCookieFactory>;
    public keepAlive: ReturnType<typeof keepAliveFactory>;
    public lockPoll: ReturnType<typeof lockPollFactory>;
    public sendReport: ReturnType<typeof sendReportFactory>;
    public sendVideo: ReturnType<typeof sendVideoFactory>;
    public updateQuickMessage: ReturnType<typeof updateQuickMessageFactory>;
    public updateArchivedChatList: ReturnType<typeof updateArchivedChatListFactory>;
    public sendSticker: ReturnType<typeof sendStickerFactory>;
    public getArchivedChatList: ReturnType<typeof getArchivedChatListFactory>;
    public updateAutoReply: ReturnType<typeof updateAutoReplyFactory>;

    public custom: ReturnType<typeof customFactory>;

    constructor(ctx: ContextSession, zpwServiceMap: ZPWServiceMap, wsUrls: string[]) {
        this.zpwServiceMap = zpwServiceMap;
        this.listener = new Listener(ctx, wsUrls);

        this.changeGroupOwner = changeGroupOwnerFactory(ctx, this);
        this.getLabels = getLabelsFactory(ctx, this);
        this.acceptFriendRequest = acceptFriendRequestFactory(ctx, this);
        this.resetHiddenConversPin = resetHiddenConversPinFactory(ctx, this);
        this.getGroupLinkInfo = getGroupLinkInfoFactory(ctx, this);
        this.editNote = editNoteFactory(ctx, this);
        this.sharePoll = sharePollFactory(ctx, this);
        this.updateAutoDeleteChat = updateAutoDeleteChatFactory(ctx, this);
        this.getCloseFriends = getCloseFriendsFactory(ctx, this);
        this.votePoll = votePollFactory(ctx, this);
        this.getGroupInfo = getGroupInfoFactory(ctx, this);
        this.deleteChat = deleteChatFactory(ctx, this);
        this.removeFriend = removeFriendFactory(ctx, this);
        this.addPollOptions = addPollOptionsFactory(ctx, this);
        this.getOwnId = getOwnIdFactory(ctx, this);
        this.deleteGroupInviteBox = deleteGroupInviteBoxFactory(ctx, this);
        this.rejectFriendRequest = rejectFriendRequestFactory(ctx, this);
        this.removeGroupDeputy = removeGroupDeputyFactory(ctx, this);
        this.createNote = createNoteFactory(ctx, this);
        this.updateActiveStatus = updateActiveStatusFactory(ctx, this);
        this.blockUser = blockUserFactory(ctx, this);
        this.changeGroupAvatar = changeGroupAvatarFactory(ctx, this);
        this.deleteAutoReply = deleteAutoReplyFactory(ctx, this);
        this.getPinConversations = getPinConversationsFactory(ctx, this);
        this.updateCatalog = updateCatalogFactory(ctx, this);
        this.upgradeGroupToCommunity = upgradeGroupToCommunityFactory(ctx, this);
        this.getGroupMembersInfo = getGroupMembersInfoFactory(ctx, this);
        this.getAvatarList = getAvatarListFactory(ctx, this);
        this.getFriendRecommendations = getFriendRecommendationsFactory(ctx, this);
        this.updateProfileBio = updateProfileBioFactory(ctx, this);
        this.removeReminder = removeReminderFactory(ctx, this);
        this.sendMessage = sendMessageFactory(ctx, this);
        this.setMute = setMuteFactory(ctx, this);
        this.removeGroupBlockedMember = removeGroupBlockedMemberFactory(ctx, this);
        this.updateLang = updateLangFactory(ctx, this);
        this.undo = undoFactory(ctx, this);
        this.getHiddenConversations = getHiddenConversationsFactory(ctx, this);
        this.parseLink = parseLinkFactory(ctx, this);
        this.setPinnedConversations = setPinnedConversationsFactory(ctx, this);
        this.addUserToGroup = addUserToGroupFactory(ctx, this);
        this.disableGroupLink = disableGroupLinkFactory(ctx, this);
        this.setHiddenConversations = setHiddenConversationsFactory(ctx, this);
        this.getSettings = getSettingsFactory(ctx, this);
        this.deleteAvatar = deleteAvatarFactory(ctx, this);
        this.getGroupChatHistory = getGroupChatHistoryFactory(ctx, this);
        this.getAliasList = getAliasListFactory(ctx, this);
        this.fetchAccountInfo = fetchAccountInfoFactory(ctx, this);
        this.getProductCatalogList = getProductCatalogListFactory(ctx, this);
        this.removeQuickMessage = removeQuickMessageFactory(ctx, this);
        this.getUnreadMark = getUnreadMarkFactory(ctx, this);
        this.updateLabels = updateLabelsFactory(ctx, this);
        this.changeGroupName = changeGroupNameFactory(ctx, this);
        this.getGroupLinkDetail = getGroupLinkDetailFactory(ctx, this);
        this.getPollDetail = getPollDetailFactory(ctx, this);
        this.sendVoice = sendVoiceFactory(ctx, this);
        this.getFriendOnlines = getFriendOnlinesFactory(ctx, this);
        this.getAllGroups = getAllGroupsFactory(ctx, this);
        this.createPoll = createPollFactory(ctx, this);
        this.getPendingGroupMembers = getPendingGroupMembersFactory(ctx, this);
        this.createGroup = createGroupFactory(ctx, this);
        this.inviteUserToGroups = inviteUserToGroupsFactory(ctx, this);
        this.getListBoard = getListBoardFactory(ctx, this);
        this.getContext = getContextFactory(ctx, this);
        this.getReminderResponses = getReminderResponsesFactory(ctx, this);
        this.getAvatarUrlProfile = getAvatarUrlProfileFactory(ctx, this);
        this.getQuickMessageList = getQuickMessageListFactory(ctx, this);
        this.getBizAccount = getBizAccountFactory(ctx, this);
        this.uploadProductPhoto = uploadProductPhotoFactory(ctx, this);
        this.disperseGroup = disperseGroupFactory(ctx, this);
        this.updateSettings = updateSettingsFactory(ctx, this);
        this.uploadAttachment = uploadAttachmentFactory(ctx, this);
        this.deleteMessage = deleteMessageFactory(ctx, this);
        this.updateProductCatalog = updateProductCatalogFactory(ctx, this);
        this.createProductCatalog = createProductCatalogFactory(ctx, this);
        this.getAutoReplyList = getAutoReplyListFactory(ctx, this);
        this.reuseAvatar = reuseAvatarFactory(ctx, this);
        this.getStickerCategoryDetail = getStickerCategoryDetailFactory(ctx, this);
        this.getAllFriends = getAllFriendsFactory(ctx, this);
        this.findUser = findUserFactory(ctx, this);
        this.sendCard = sendCardFactory(ctx, this);
        this.changeAccountAvatar = changeAccountAvatarFactory(ctx, this);
        this.removeUserFromGroup = removeUserFromGroupFactory(ctx, this);
        this.removeFriendAlias = removeFriendAliasFactory(ctx, this);
        this.getFriendBoardList = getFriendBoardListFactory(ctx, this);
        this.editReminder = editReminderFactory(ctx, this);
        this.createAutoReply = createAutoReplyFactory(ctx, this);
        this.updateProfile = updateProfileFactory(ctx, this);
        this.lastOnline = lastOnlineFactory(ctx, this);
        this.addUnreadMark = addUnreadMarkFactory(ctx, this);
        this.createCatalog = createCatalogFactory(ctx, this);
        this.getStickers = getStickersFactory(ctx, this);
        this.unblockUser = unblockUserFactory(ctx, this);
        this.getQR = getQRFactory(ctx, this);
        this.joinGroupInviteBox = joinGroupInviteBoxFactory(ctx, this);
        this.addReaction = addReactionFactory(ctx, this);
        this.getAutoDeleteChat = getAutoDeleteChatFactory(ctx, this);
        this.reviewPendingMemberRequest = reviewPendingMemberRequestFactory(ctx, this);
        this.searchSticker = searchStickerFactory(ctx, this);
        this.getUserInfo = getUserInfoFactory(ctx, this);
        this.getMultiUsersByPhones = getMultiUsersByPhonesFactory(ctx, this);
        this.updateGroupSettings = updateGroupSettingsFactory(ctx, this);
        this.getFriendRequestStatus = getFriendRequestStatusFactory(ctx, this);
        this.sendBankCard = sendBankCardFactory(ctx, this);
        this.getFullAvatar = getFullAvatarFactory(ctx, this);
        this.getSentFriendRequest = getSentFriendRequestFactory(ctx, this);
        this.getGroupBlockedMember = getGroupBlockedMemberFactory(ctx, this);
        this.sendFriendRequest = sendFriendRequestFactory(ctx, this);
        this.getReminder = getReminderFactory(ctx, this);
        this.getListReminder = getListReminderFactory(ctx, this);
        this.deleteCatalog = deleteCatalogFactory(ctx, this);
        this.sendSeenEvent = sendSeenEventFactory(ctx, this);
        this.updateHiddenConversPin = updateHiddenConversPinFactory(ctx, this);
        this.blockViewFeed = blockViewFeedFactory(ctx, this);
        this.addGroupBlockedMember = addGroupBlockedMemberFactory(ctx, this);
        this.sendDeliveredEvent = sendDeliveredEventFactory(ctx, this);
        this.removeUnreadMark = removeUnreadMarkFactory(ctx, this);
        this.leaveGroup = leaveGroupFactory(ctx, this);
        this.getGroupInviteBoxInfo = getGroupInviteBoxInfoFactory(ctx, this);
        this.addQuickMessage = addQuickMessageFactory(ctx, this);
        this.sendLink = sendLinkFactory(ctx, this);
        this.getMute = getMuteFactory(ctx, this);
        this.sendTypingEvent = sendTypingEventFactory(ctx, this);
        this.getCatalogList = getCatalogListFactory(ctx, this);
        this.getRelatedFriendGroup = getRelatedFriendGroupFactory(ctx, this);
        this.deleteProductCatalog = deleteProductCatalogFactory(ctx, this);
        this.getGroupInviteBoxList = getGroupInviteBoxListFactory(ctx, this);
        this.findUserByUsername = findUserByUsernameFactory(ctx, this);
        this.enableGroupLink = enableGroupLinkFactory(ctx, this);
        this.changeFriendAlias = changeFriendAliasFactory(ctx, this);
        this.forwardMessage = forwardMessageFactory(ctx, this);
        this.undoFriendRequest = undoFriendRequestFactory(ctx, this);
        this.joinGroupLink = joinGroupLinkFactory(ctx, this);
        this.getStickersDetail = getStickersDetailFactory(ctx, this);
        this.createReminder = createReminderFactory(ctx, this);
        this.addGroupDeputy = addGroupDeputyFactory(ctx, this);
        this.getCookie = getCookieFactory(ctx, this);
        this.keepAlive = keepAliveFactory(ctx, this);
        this.lockPoll = lockPollFactory(ctx, this);
        this.sendReport = sendReportFactory(ctx, this);
        this.sendVideo = sendVideoFactory(ctx, this);
        this.updateQuickMessage = updateQuickMessageFactory(ctx, this);
        this.updateArchivedChatList = updateArchivedChatListFactory(ctx, this);
        this.sendSticker = sendStickerFactory(ctx, this);
        this.getArchivedChatList = getArchivedChatListFactory(ctx, this);
        this.updateAutoReply = updateAutoReplyFactory(ctx, this);

        this.custom = customFactory(ctx, this);
    }
}
